import { CONTACT_EMAIL, LegalPageLayout, LegalSection } from "@/features/legal/LegalPageLayout";

export function PrivacyPolicyPage() {
  return (
    <LegalPageLayout
      title="Privacy Policy"
      effectiveDate="August 11, 2026"
      summary={
        <p>
          We collect the profile, resume, and account information you give us to run the Service,
          including sending some of it to third-party AI providers to power features you use. We
          don't sell your data or show you third-party ads. You can access and correct your
          information from Settings, and permanently delete your account and all your data at any
          time.
        </p>
      }
    >
      <LegalSection title="1. Information we collect">
        <p>You provide most of what we collect directly:</p>
        <ul className="ml-5 list-disc space-y-1">
          <li>
            <strong>Account information</strong>: name, email address, and a hashed (never
            plaintext) password.
          </li>
          <li>
            <strong>Optional profile information</strong>: phone number, mailing address, country,
            and language preference.
          </li>
          <li>
            <strong>Career profile content</strong>: headline, summary, work experience, education,
            certifications, skills, career goals, achievements, and any resumes or profile photos
            you upload.
          </li>
          <li>
            <strong>AI Career Coach conversations</strong>: the messages you send to and receive
            from the in-app AI chat.
          </li>
        </ul>
        <p>We also automatically collect limited technical information needed to operate the Service:</p>
        <ul className="ml-5 list-disc space-y-1">
          <li>Login timestamps and basic request metadata (e.g. for security and audit logging);</li>
          <li>
            Standard web server logs (e.g. IP address, browser type) generated by normal HTTP
            traffic.
          </li>
        </ul>
        <p>
          We do not currently use third-party analytics or advertising trackers. If that changes,
          we will update this policy first.
        </p>
      </LegalSection>

      <LegalSection title="2. How we use your information">
        <p>We use your information to:</p>
        <ul className="ml-5 list-disc space-y-1">
          <li>Create and maintain your account, and authenticate you when you sign in;</li>
          <li>Provide the core Service — building and displaying your career profile;</li>
          <li>
            Power AI features (resume extraction, skill gap analysis, the AI Career Coach) by
            sending relevant profile/resume/chat content to an AI provider, as described below;
          </li>
          <li>Send you account-related email, such as email verification and password reset;</li>
          <li>Maintain the security and integrity of the Service, including audit logging;</li>
          <li>Comply with legal obligations where applicable.</li>
        </ul>
      </LegalSection>

      <LegalSection title="3. Third parties we share information with">
        <p>
          We do not sell your personal information. We share information only as needed to
          actually run the Service, with the following categories of service providers:
        </p>
        <ul className="ml-5 list-disc space-y-1">
          <li>
            <strong>AI providers (Anthropic, Groq)</strong>: when you use an AI-powered feature
            (resume extraction, gap analysis, the AI Career Coach) and your account is configured
            to use one of these providers, the relevant profile, resume, or chat text is sent to
            that provider to generate a response. You can choose which AI model powers your
            account in Settings; a self-hosted, local model option is also available that does not
            send your data to any external AI provider.
          </li>
          <li>
            <strong>Firebase (Google)</strong>: if you use phone-number sign-in, your phone number
            is shared with Firebase Authentication solely to verify a one-time SMS code. Firebase
            does not receive any other profile data.
          </li>
          <li>
            <strong>Resend</strong>: our transactional email provider — used to deliver
            verification and password-reset emails to the email address you provide.
          </li>
        </ul>
        <p>
          We do not share your information with data brokers, advertisers, or any other third
          party for their own marketing purposes.
        </p>
      </LegalSection>

      <LegalSection title="4. Data storage and security">
        <p>
          Your information is stored on secured servers located in the United States. We use
          industry-standard measures — including encrypted password storage, access controls, and
          tenant isolation at the database level — to protect your information. No method of
          storage or transmission is completely secure, and we cannot guarantee absolute security.
        </p>
      </LegalSection>

      <LegalSection title="5. Data retention and deletion">
        <p>
          We retain your information for as long as your account is active. You can permanently
          delete your account at any time from Settings → Account. Deletion is immediate and
          real — your account, career profile, resumes, and chat history are removed from our
          production database right away, with no recovery period or delayed purge.
        </p>
      </LegalSection>

      <LegalSection title="6. Your rights">
        <p>You can, at any time:</p>
        <ul className="ml-5 list-disc space-y-1">
          <li>
            <strong>Access and correct</strong> your account and profile information directly from
            Settings;
          </li>
          <li>
            <strong>Delete</strong> your account and all associated data, immediately and
            permanently, from Settings → Account;
          </li>
          <li>
            <strong>Ask questions or raise concerns</strong> about your information by emailing{" "}
            <a href={`mailto:${CONTACT_EMAIL}`} className="underline">
              {CONTACT_EMAIL}
            </a>
            .
          </li>
        </ul>
        <p>
          If you are located in the European Economic Area, the United Kingdom, or California, you
          may have additional rights under GDPR or the CCPA (such as the right to data
          portability or to opt out of certain processing) — contact us at the email above and we
          will address your request.
        </p>
      </LegalSection>

      <LegalSection title="7. Children's privacy">
        <p>
          The Service is not directed to, and we do not knowingly collect information from,
          anyone under 18 years old. If you believe a minor has provided us information, contact
          us and we will delete it.
        </p>
      </LegalSection>

      <LegalSection title="8. International users">
        <p>
          The Service is operated from and your information is processed in the United States. If
          you access the Service from outside the United States, you understand that your
          information will be transferred to and processed in the United States, which may have
          different data protection laws than your home jurisdiction.
        </p>
      </LegalSection>

      <LegalSection title="9. Changes to this policy">
        <p>
          We may update this Privacy Policy from time to time. If we make material changes, we
          will notify you by email or through an in-app notice before the changes take effect.
        </p>
      </LegalSection>

      <LegalSection title="10. Contact">
        <p>
          Questions about this Privacy Policy or your information can be sent to{" "}
          <a href={`mailto:${CONTACT_EMAIL}`} className="underline">
            {CONTACT_EMAIL}
          </a>
          .
        </p>
      </LegalSection>
    </LegalPageLayout>
  );
}
