"""Repository interfaces for the Career Profile bounded context.

Application services depend only on these Protocols — see
app/domain/identity/repositories.py for the established pattern this
follows.

Every orderable entity's Protocol includes `move(direction)` — reorders
the item relative to its neighbors within its scope (profile or user).
See app/adapters/db/reorder.py for the shared implementation every
concrete repository delegates to.
"""

from __future__ import annotations

from typing import Literal, Protocol
from uuid import UUID

from app.domain.career_profile.entities import (
    CareerGoal,
    CareerHighlight,
    CareerProfile,
    CareerProfileVersion,
    Certification,
    Education,
    Experience,
    KeyAchievement,
    PeerEndorsement,
    TargetRole,
)

Direction = Literal["up", "down"]


class CareerProfileRepository(Protocol):
    async def create(self, profile: CareerProfile) -> CareerProfile: ...
    async def get_by_user_id(
        self, tenant_id: UUID, user_id: UUID, target_role_id: UUID | None = None
    ) -> CareerProfile | None: ...
    async def get_by_id(self, tenant_id: UUID, profile_id: UUID) -> CareerProfile | None: ...
    async def update(self, profile: CareerProfile) -> CareerProfile: ...


class CareerProfileVersionRepository(Protocol):
    async def create(self, version: CareerProfileVersion) -> CareerProfileVersion: ...
    async def list_for_profile(
        self, career_profile_id: UUID, *, limit: int = 50
    ) -> list[CareerProfileVersion]: ...


class ExperienceRepository(Protocol):
    async def create(self, experience: Experience) -> Experience: ...
    async def get_by_id(self, tenant_id: UUID, experience_id: UUID) -> Experience | None: ...
    async def list_for_profile(
        self, tenant_id: UUID, career_profile_id: UUID
    ) -> list[Experience]: ...
    async def update(self, experience: Experience) -> Experience: ...
    async def soft_delete(self, tenant_id: UUID, experience_id: UUID) -> None: ...
    async def soft_delete_all_for_profile(
        self, tenant_id: UUID, career_profile_id: UUID
    ) -> None: ...
    async def move(self, tenant_id: UUID, experience_id: UUID, direction: Direction) -> None: ...


class EducationRepository(Protocol):
    async def create(self, education: Education) -> Education: ...
    async def get_by_id(self, tenant_id: UUID, education_id: UUID) -> Education | None: ...
    async def list_for_profile(
        self, tenant_id: UUID, career_profile_id: UUID
    ) -> list[Education]: ...
    async def update(self, education: Education) -> Education: ...
    async def soft_delete(self, tenant_id: UUID, education_id: UUID) -> None: ...
    async def soft_delete_all_for_profile(
        self, tenant_id: UUID, career_profile_id: UUID
    ) -> None: ...
    async def move(self, tenant_id: UUID, education_id: UUID, direction: Direction) -> None: ...


class CertificationRepository(Protocol):
    async def create(self, certification: Certification) -> Certification: ...
    async def get_by_id(
        self, tenant_id: UUID, certification_id: UUID
    ) -> Certification | None: ...
    async def list_for_profile(
        self, tenant_id: UUID, career_profile_id: UUID
    ) -> list[Certification]: ...
    async def update(self, certification: Certification) -> Certification: ...
    async def soft_delete(self, tenant_id: UUID, certification_id: UUID) -> None: ...
    async def soft_delete_all_for_profile(
        self, tenant_id: UUID, career_profile_id: UUID
    ) -> None: ...
    async def move(
        self, tenant_id: UUID, certification_id: UUID, direction: Direction
    ) -> None: ...


class CareerGoalRepository(Protocol):
    async def create(self, goal: CareerGoal) -> CareerGoal: ...
    async def get_by_id(self, tenant_id: UUID, goal_id: UUID) -> CareerGoal | None: ...
    async def list_for_user(self, tenant_id: UUID, user_id: UUID) -> list[CareerGoal]: ...
    async def update(self, goal: CareerGoal) -> CareerGoal: ...
    async def soft_delete(self, tenant_id: UUID, goal_id: UUID) -> None: ...
    async def soft_delete_all_for_user(self, tenant_id: UUID, user_id: UUID) -> None: ...
    async def move(self, tenant_id: UUID, goal_id: UUID, direction: Direction) -> None: ...


class CareerHighlightRepository(Protocol):
    async def create(self, highlight: CareerHighlight) -> CareerHighlight: ...
    async def get_by_id(self, tenant_id: UUID, highlight_id: UUID) -> CareerHighlight | None: ...
    async def list_for_profile(
        self, tenant_id: UUID, career_profile_id: UUID
    ) -> list[CareerHighlight]: ...
    async def update(self, highlight: CareerHighlight) -> CareerHighlight: ...
    async def soft_delete(self, tenant_id: UUID, highlight_id: UUID) -> None: ...
    async def soft_delete_all_for_profile(
        self, tenant_id: UUID, career_profile_id: UUID
    ) -> None: ...
    async def move(self, tenant_id: UUID, highlight_id: UUID, direction: Direction) -> None: ...


class KeyAchievementRepository(Protocol):
    async def create(self, achievement: KeyAchievement) -> KeyAchievement: ...
    async def get_by_id(self, tenant_id: UUID, achievement_id: UUID) -> KeyAchievement | None: ...
    async def list_for_profile(
        self, tenant_id: UUID, career_profile_id: UUID
    ) -> list[KeyAchievement]: ...
    async def update(self, achievement: KeyAchievement) -> KeyAchievement: ...
    async def soft_delete(self, tenant_id: UUID, achievement_id: UUID) -> None: ...
    async def soft_delete_all_for_profile(
        self, tenant_id: UUID, career_profile_id: UUID
    ) -> None: ...
    async def move(
        self, tenant_id: UUID, achievement_id: UUID, direction: Direction
    ) -> None: ...


class PeerEndorsementRepository(Protocol):
    async def create(self, endorsement: PeerEndorsement) -> PeerEndorsement: ...
    async def get_by_id(
        self, tenant_id: UUID, endorsement_id: UUID
    ) -> PeerEndorsement | None: ...
    async def list_for_profile(
        self, tenant_id: UUID, career_profile_id: UUID
    ) -> list[PeerEndorsement]: ...
    async def update(self, endorsement: PeerEndorsement) -> PeerEndorsement: ...
    async def soft_delete(self, tenant_id: UUID, endorsement_id: UUID) -> None: ...
    async def soft_delete_all_for_profile(
        self, tenant_id: UUID, career_profile_id: UUID
    ) -> None: ...
    async def move(
        self, tenant_id: UUID, endorsement_id: UUID, direction: Direction
    ) -> None: ...


class TargetRoleRepository(Protocol):
    async def create(self, target_role: TargetRole) -> TargetRole: ...
    async def get_by_id(self, tenant_id: UUID, target_role_id: UUID) -> TargetRole | None: ...
    async def list_for_user(self, tenant_id: UUID, user_id: UUID) -> list[TargetRole]: ...
    async def update(self, target_role: TargetRole) -> TargetRole: ...
    async def soft_delete(self, tenant_id: UUID, target_role_id: UUID) -> None: ...
