/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Liveness check: process is running and settings loaded.
         */
        get: operations["health_check_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identity/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register Tenant */
        post: operations["register_tenant_api_v1_identity_tenants_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identity/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_identity_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identity/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_api_v1_identity_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Me */
        patch: operations["update_me_api_v1_identity_me_patch"];
        trace?: never;
    };
    "/api/v1/identity/audit-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Audit Events */
        get: operations["list_audit_events_api_v1_identity_audit_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identity/feature-flags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Feature Flags */
        get: operations["list_feature_flags_api_v1_identity_feature_flags_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/career-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Career Profile */
        get: operations["get_career_profile_api_v1_career_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Career Profile */
        patch: operations["update_career_profile_api_v1_career_profile_patch"];
        trace?: never;
    };
    "/api/v1/career-profile/photo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Profile Photo */
        post: operations["upload_profile_photo_api_v1_career_profile_photo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/career-profile/experiences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Experiences */
        get: operations["list_experiences_api_v1_career_profile_experiences_get"];
        put?: never;
        /** Add Experience */
        post: operations["add_experience_api_v1_career_profile_experiences_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/career-profile/experiences/{experience_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Experience */
        delete: operations["delete_experience_api_v1_career_profile_experiences__experience_id__delete"];
        options?: never;
        head?: never;
        /** Update Experience */
        patch: operations["update_experience_api_v1_career_profile_experiences__experience_id__patch"];
        trace?: never;
    };
    "/api/v1/career-profile/experiences/{experience_id}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Move Experience */
        post: operations["move_experience_api_v1_career_profile_experiences__experience_id__move_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/career-profile/educations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Educations */
        get: operations["list_educations_api_v1_career_profile_educations_get"];
        put?: never;
        /** Add Education */
        post: operations["add_education_api_v1_career_profile_educations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/career-profile/educations/{education_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Education */
        delete: operations["delete_education_api_v1_career_profile_educations__education_id__delete"];
        options?: never;
        head?: never;
        /** Update Education */
        patch: operations["update_education_api_v1_career_profile_educations__education_id__patch"];
        trace?: never;
    };
    "/api/v1/career-profile/educations/{education_id}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Move Education */
        post: operations["move_education_api_v1_career_profile_educations__education_id__move_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/career-profile/certifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Certifications */
        get: operations["list_certifications_api_v1_career_profile_certifications_get"];
        put?: never;
        /** Add Certification */
        post: operations["add_certification_api_v1_career_profile_certifications_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/career-profile/certifications/{certification_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Certification */
        delete: operations["delete_certification_api_v1_career_profile_certifications__certification_id__delete"];
        options?: never;
        head?: never;
        /** Update Certification */
        patch: operations["update_certification_api_v1_career_profile_certifications__certification_id__patch"];
        trace?: never;
    };
    "/api/v1/career-profile/certifications/{certification_id}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Move Certification */
        post: operations["move_certification_api_v1_career_profile_certifications__certification_id__move_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/career-profile/highlights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Career Highlights */
        get: operations["list_career_highlights_api_v1_career_profile_highlights_get"];
        put?: never;
        /** Add Career Highlight */
        post: operations["add_career_highlight_api_v1_career_profile_highlights_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/career-profile/highlights/{highlight_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Career Highlight */
        delete: operations["delete_career_highlight_api_v1_career_profile_highlights__highlight_id__delete"];
        options?: never;
        head?: never;
        /** Update Career Highlight */
        patch: operations["update_career_highlight_api_v1_career_profile_highlights__highlight_id__patch"];
        trace?: never;
    };
    "/api/v1/career-profile/highlights/{highlight_id}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Move Career Highlight */
        post: operations["move_career_highlight_api_v1_career_profile_highlights__highlight_id__move_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/career-profile/achievements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Key Achievements */
        get: operations["list_key_achievements_api_v1_career_profile_achievements_get"];
        put?: never;
        /** Add Key Achievement */
        post: operations["add_key_achievement_api_v1_career_profile_achievements_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/career-profile/achievements/{achievement_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Key Achievement */
        delete: operations["delete_key_achievement_api_v1_career_profile_achievements__achievement_id__delete"];
        options?: never;
        head?: never;
        /** Update Key Achievement */
        patch: operations["update_key_achievement_api_v1_career_profile_achievements__achievement_id__patch"];
        trace?: never;
    };
    "/api/v1/career-profile/achievements/{achievement_id}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Move Key Achievement */
        post: operations["move_key_achievement_api_v1_career_profile_achievements__achievement_id__move_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/career-profile/endorsements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Peer Endorsements */
        get: operations["list_peer_endorsements_api_v1_career_profile_endorsements_get"];
        put?: never;
        /** Add Peer Endorsement */
        post: operations["add_peer_endorsement_api_v1_career_profile_endorsements_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/career-profile/endorsements/{endorsement_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Peer Endorsement */
        delete: operations["delete_peer_endorsement_api_v1_career_profile_endorsements__endorsement_id__delete"];
        options?: never;
        head?: never;
        /** Update Peer Endorsement */
        patch: operations["update_peer_endorsement_api_v1_career_profile_endorsements__endorsement_id__patch"];
        trace?: never;
    };
    "/api/v1/career-profile/endorsements/{endorsement_id}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Move Peer Endorsement */
        post: operations["move_peer_endorsement_api_v1_career_profile_endorsements__endorsement_id__move_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/career-goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Career Goals */
        get: operations["list_career_goals_api_v1_career_goals_get"];
        put?: never;
        /** Add Career Goal */
        post: operations["add_career_goal_api_v1_career_goals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/career-goals/{goal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Career Goal */
        delete: operations["delete_career_goal_api_v1_career_goals__goal_id__delete"];
        options?: never;
        head?: never;
        /** Update Career Goal */
        patch: operations["update_career_goal_api_v1_career_goals__goal_id__patch"];
        trace?: never;
    };
    "/api/v1/career-goals/{goal_id}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Move Career Goal */
        post: operations["move_career_goal_api_v1_career_goals__goal_id__move_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/career-profile/target-roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Target Roles */
        get: operations["list_target_roles_api_v1_career_profile_target_roles_get"];
        put?: never;
        /** Add Target Role */
        post: operations["add_target_role_api_v1_career_profile_target_roles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/career-profile/target-roles/{target_role_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Target Role */
        delete: operations["delete_target_role_api_v1_career_profile_target_roles__target_role_id__delete"];
        options?: never;
        head?: never;
        /** Update Target Role */
        patch: operations["update_target_role_api_v1_career_profile_target_roles__target_role_id__patch"];
        trace?: never;
    };
    "/api/v1/career-profile/target-roles/{target_role_id}/required-skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Required Skill */
        post: operations["add_required_skill_api_v1_career_profile_target_roles__target_role_id__required_skills_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/career-profile/target-roles/{target_role_id}/required-skills/{skill_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Required Skill */
        delete: operations["remove_required_skill_api_v1_career_profile_target_roles__target_role_id__required_skills__skill_name__delete"];
        options?: never;
        head?: never;
        /** Rename Required Skill */
        patch: operations["rename_required_skill_api_v1_career_profile_target_roles__target_role_id__required_skills__skill_name__patch"];
        trace?: never;
    };
    "/api/v1/chat/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send Chat Message */
        post: operations["send_chat_message_api_v1_chat_messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quote-of-the-day": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Quote Of The Day */
        get: operations["get_quote_of_the_day_api_v1_quote_of_the_day_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/skills/gap-analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Gap Analysis */
        get: operations["get_gap_analysis_api_v1_skills_gap_analysis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddRequiredSkillRequest */
        AddRequiredSkillRequest: {
            /** Name */
            name: string;
        };
        /** AuditEventResponse */
        AuditEventResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Action */
            action: string;
            /** Resource Type */
            resource_type: string;
            /** Resource Id */
            resource_id: string | null;
            /** Occurred At */
            occurred_at: string;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
        };
        /** Body_upload_profile_photo_api_v1_career_profile_photo_post */
        Body_upload_profile_photo_api_v1_career_profile_photo_post: {
            /** File */
            file: string;
        };
        /** CareerGoalRequest */
        CareerGoalRequest: {
            /** Target Role */
            target_role: string;
            /** Target Date */
            target_date?: string | null;
            /** Description */
            description?: string | null;
        };
        /** CareerGoalResponse */
        CareerGoalResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Target Role */
            target_role: string;
            /** Target Date */
            target_date: string | null;
            /** Status */
            status: string;
            /** Description */
            description: string | null;
            /** Display Order */
            display_order: number;
        };
        /** CareerGoalUpdateRequest */
        CareerGoalUpdateRequest: {
            /** Target Role */
            target_role: string;
            /** Target Date */
            target_date?: string | null;
            /** Description */
            description?: string | null;
            /** Status */
            status: string;
        };
        /** CareerHighlightRequest */
        CareerHighlightRequest: {
            /** Title */
            title: string;
            /** Company */
            company?: string | null;
            /** Description */
            description?: string | null;
            /** Occurred On */
            occurred_on?: string | null;
        };
        /** CareerHighlightResponse */
        CareerHighlightResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Company */
            company: string | null;
            /** Description */
            description: string | null;
            /** Occurred On */
            occurred_on: string | null;
            /** Display Order */
            display_order: number;
        };
        /** CareerProfileResponse */
        CareerProfileResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Current Version */
            current_version: number;
            /** Headline */
            headline: string | null;
            /** Summary */
            summary: string | null;
            /** Career Readiness Score */
            career_readiness_score: number | null;
            /** Photo Url */
            photo_url: string | null;
            /** Core Competencies */
            core_competencies: string[];
            /** Section Order */
            section_order: string[] | null;
        };
        /** CertificationRequest */
        CertificationRequest: {
            /** Name */
            name: string;
            /** Issuing Organization */
            issuing_organization: string;
            /** Issue Date */
            issue_date?: string | null;
            /** Expiration Date */
            expiration_date?: string | null;
            /** Credential Id */
            credential_id?: string | null;
            /** Credential Url */
            credential_url?: string | null;
        };
        /** CertificationResponse */
        CertificationResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Issuing Organization */
            issuing_organization: string;
            /** Issue Date */
            issue_date: string | null;
            /** Expiration Date */
            expiration_date: string | null;
            /** Credential Id */
            credential_id: string | null;
            /** Credential Url */
            credential_url: string | null;
            /** Display Order */
            display_order: number;
        };
        /** ChatMessageResponse */
        ChatMessageResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Role */
            role: string;
            /** Content */
            content: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** CurrentUserResponse */
        CurrentUserResponse: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /** Org Id */
            org_id: string | null;
            /** Email */
            email: string;
            /** Full Name */
            full_name: string;
            /** Salutation */
            salutation: string | null;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Phone Number */
            phone_number: string | null;
            /** Country */
            country: string | null;
            /** Language */
            language: string | null;
            /** Address Line1 */
            address_line1: string | null;
            /** Address Line2 */
            address_line2: string | null;
            /** City */
            city: string | null;
            /** State */
            state: string | null;
            /** Postal Code */
            postal_code: string | null;
            /** Roles */
            roles: string[];
        };
        /** EducationRequest */
        EducationRequest: {
            /** Institution */
            institution: string;
            /** Degree */
            degree?: string | null;
            /** Field Of Study */
            field_of_study?: string | null;
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
            /** Description */
            description?: string | null;
        };
        /** EducationResponse */
        EducationResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Institution */
            institution: string;
            /** Degree */
            degree: string | null;
            /** Field Of Study */
            field_of_study: string | null;
            /** Start Date */
            start_date: string | null;
            /** End Date */
            end_date: string | null;
            /** Description */
            description: string | null;
            /** Display Order */
            display_order: number;
        };
        /** ExperienceRequest */
        ExperienceRequest: {
            /** Title */
            title: string;
            /** Company */
            company: string;
            /** Location */
            location?: string | null;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /** End Date */
            end_date?: string | null;
            /** Description */
            description?: string | null;
        };
        /** ExperienceResponse */
        ExperienceResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Company */
            company: string;
            /** Location */
            location: string | null;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /** End Date */
            end_date: string | null;
            /** Description */
            description: string | null;
            /** Display Order */
            display_order: number;
        };
        /** FeatureFlagResponse */
        FeatureFlagResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Key */
            key: string;
            /** Enabled */
            enabled: boolean;
            /** Config */
            config: {
                [key: string]: unknown;
            };
            /** Is Global Default */
            is_global_default: boolean;
        };
        /** GapAnalysisResponse */
        GapAnalysisResponse: {
            /** Target Role Gaps */
            target_role_gaps: components["schemas"]["TargetRoleGapResponse"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** App Name */
            app_name: string;
            /** App Env */
            app_env: string;
        };
        /** KeyAchievementRequest */
        KeyAchievementRequest: {
            /** Title */
            title: string;
            /** Company */
            company?: string | null;
            /** Description */
            description?: string | null;
            /** Occurred On */
            occurred_on?: string | null;
        };
        /** KeyAchievementResponse */
        KeyAchievementResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Company */
            company: string | null;
            /** Description */
            description: string | null;
            /** Occurred On */
            occurred_on: string | null;
            /** Display Order */
            display_order: number;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Subdomain */
            subdomain: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /** Access Token */
            access_token: string;
            /** Token Type */
            token_type: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /** Email */
            email: string;
            /** Full Name */
            full_name: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Salutation */
            salutation: string | null;
            /** Last Login At */
            last_login_at: string | null;
            /** Roles */
            roles: string[];
        };
        /**
         * MoveRequest
         * @description Shared by every reorderable entity's move endpoint.
         */
        MoveRequest: {
            /** Direction */
            direction: string;
        };
        /** PeerEndorsementRequest */
        PeerEndorsementRequest: {
            /** Recommender Name */
            recommender_name: string;
            /** Recommender Title */
            recommender_title?: string | null;
            /** Relationship */
            relationship?: string | null;
            /** Content */
            content: string;
        };
        /** PeerEndorsementResponse */
        PeerEndorsementResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Recommender Name */
            recommender_name: string;
            /** Recommender Title */
            recommender_title: string | null;
            /** Relationship */
            relationship: string | null;
            /** Content */
            content: string;
            /** Display Order */
            display_order: number;
        };
        /** PhotoUploadResponse */
        PhotoUploadResponse: {
            /** Photo Url */
            photo_url: string;
        };
        /** QuoteOfTheDayResponse */
        QuoteOfTheDayResponse: {
            /** Content */
            content: string;
            /** Author */
            author: string | null;
        };
        /** RegisterTenantRequest */
        RegisterTenantRequest: {
            /** Tenant Name */
            tenant_name: string;
            /** Subdomain */
            subdomain: string;
            /** Organization Name */
            organization_name: string;
            /**
             * Admin Email
             * Format: email
             */
            admin_email: string;
            /** Admin Salutation */
            admin_salutation?: string | null;
            /** Admin First Name */
            admin_first_name: string;
            /** Admin Last Name */
            admin_last_name: string;
            /** Admin Password */
            admin_password: string;
        };
        /** RegisterTenantResponse */
        RegisterTenantResponse: {
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /**
             * Organization Id
             * Format: uuid
             */
            organization_id: string;
            /**
             * Admin User Id
             * Format: uuid
             */
            admin_user_id: string;
            /** Admin Email */
            admin_email: string;
        };
        /** SendChatMessageRequest */
        SendChatMessageRequest: {
            /** Conversation Id */
            conversation_id?: string | null;
            /** Content */
            content: string;
        };
        /** SendChatMessageResponse */
        SendChatMessageResponse: {
            /**
             * Conversation Id
             * Format: uuid
             */
            conversation_id: string;
            user_message: components["schemas"]["ChatMessageResponse"];
            assistant_message: components["schemas"]["ChatMessageResponse"];
        };
        /** TargetRoleGapResponse */
        TargetRoleGapResponse: {
            /**
             * Target Role Id
             * Format: uuid
             */
            target_role_id: string;
            /** Role Name */
            role_name: string;
            /** Tag */
            tag: string;
            /** Missing Skills */
            missing_skills: string[];
        };
        /** TargetRoleRequest */
        TargetRoleRequest: {
            /** Role Name */
            role_name: string;
            /** Tag */
            tag: string;
        };
        /** TargetRoleResponse */
        TargetRoleResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Role Name */
            role_name: string;
            /** Tag */
            tag: string;
            /** Required Skills */
            required_skills: string[];
        };
        /** UpdateCareerProfileRequest */
        UpdateCareerProfileRequest: {
            /** Headline */
            headline?: string | null;
            /** Summary */
            summary?: string | null;
            /** Core Competencies */
            core_competencies?: string[] | null;
            /** Section Order */
            section_order?: string[] | null;
        };
        /** UpdateCurrentUserRequest */
        UpdateCurrentUserRequest: {
            /** Salutation */
            salutation?: string | null;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Phone Number */
            phone_number?: string | null;
            /** Country */
            country?: string | null;
            /** Language */
            language?: string | null;
            /** Address Line1 */
            address_line1?: string | null;
            /** Address Line2 */
            address_line2?: string | null;
            /** City */
            city?: string | null;
            /** State */
            state?: string | null;
            /** Postal Code */
            postal_code?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    register_tenant_api_v1_identity_tenants_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterTenantRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterTenantResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_identity_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_api_v1_identity_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserResponse"];
                };
            };
        };
    };
    update_me_api_v1_identity_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCurrentUserRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_audit_events_api_v1_identity_audit_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEventResponse"][];
                };
            };
        };
    };
    list_feature_flags_api_v1_identity_feature_flags_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureFlagResponse"][];
                };
            };
        };
    };
    get_career_profile_api_v1_career_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CareerProfileResponse"];
                };
            };
        };
    };
    update_career_profile_api_v1_career_profile_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCareerProfileRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CareerProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_profile_photo_api_v1_career_profile_photo_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_profile_photo_api_v1_career_profile_photo_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_experiences_api_v1_career_profile_experiences_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperienceResponse"][];
                };
            };
        };
    };
    add_experience_api_v1_career_profile_experiences_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExperienceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperienceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_experience_api_v1_career_profile_experiences__experience_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experience_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_experience_api_v1_career_profile_experiences__experience_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experience_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExperienceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperienceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    move_experience_api_v1_career_profile_experiences__experience_id__move_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experience_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperienceResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_educations_api_v1_career_profile_educations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EducationResponse"][];
                };
            };
        };
    };
    add_education_api_v1_career_profile_educations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EducationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EducationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_education_api_v1_career_profile_educations__education_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                education_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_education_api_v1_career_profile_educations__education_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                education_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EducationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EducationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    move_education_api_v1_career_profile_educations__education_id__move_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                education_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EducationResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_certifications_api_v1_career_profile_certifications_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CertificationResponse"][];
                };
            };
        };
    };
    add_certification_api_v1_career_profile_certifications_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CertificationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CertificationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_certification_api_v1_career_profile_certifications__certification_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                certification_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_certification_api_v1_career_profile_certifications__certification_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                certification_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CertificationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CertificationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    move_certification_api_v1_career_profile_certifications__certification_id__move_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                certification_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CertificationResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_career_highlights_api_v1_career_profile_highlights_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CareerHighlightResponse"][];
                };
            };
        };
    };
    add_career_highlight_api_v1_career_profile_highlights_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CareerHighlightRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CareerHighlightResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_career_highlight_api_v1_career_profile_highlights__highlight_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                highlight_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_career_highlight_api_v1_career_profile_highlights__highlight_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                highlight_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CareerHighlightRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CareerHighlightResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    move_career_highlight_api_v1_career_profile_highlights__highlight_id__move_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                highlight_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CareerHighlightResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_key_achievements_api_v1_career_profile_achievements_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeyAchievementResponse"][];
                };
            };
        };
    };
    add_key_achievement_api_v1_career_profile_achievements_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KeyAchievementRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeyAchievementResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_key_achievement_api_v1_career_profile_achievements__achievement_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                achievement_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_key_achievement_api_v1_career_profile_achievements__achievement_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                achievement_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KeyAchievementRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeyAchievementResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    move_key_achievement_api_v1_career_profile_achievements__achievement_id__move_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                achievement_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeyAchievementResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_peer_endorsements_api_v1_career_profile_endorsements_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PeerEndorsementResponse"][];
                };
            };
        };
    };
    add_peer_endorsement_api_v1_career_profile_endorsements_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PeerEndorsementRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PeerEndorsementResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_peer_endorsement_api_v1_career_profile_endorsements__endorsement_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                endorsement_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_peer_endorsement_api_v1_career_profile_endorsements__endorsement_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                endorsement_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PeerEndorsementRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PeerEndorsementResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    move_peer_endorsement_api_v1_career_profile_endorsements__endorsement_id__move_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                endorsement_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PeerEndorsementResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_career_goals_api_v1_career_goals_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CareerGoalResponse"][];
                };
            };
        };
    };
    add_career_goal_api_v1_career_goals_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CareerGoalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CareerGoalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_career_goal_api_v1_career_goals__goal_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_career_goal_api_v1_career_goals__goal_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CareerGoalUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CareerGoalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    move_career_goal_api_v1_career_goals__goal_id__move_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CareerGoalResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_target_roles_api_v1_career_profile_target_roles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TargetRoleResponse"][];
                };
            };
        };
    };
    add_target_role_api_v1_career_profile_target_roles_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TargetRoleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TargetRoleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_target_role_api_v1_career_profile_target_roles__target_role_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                target_role_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_target_role_api_v1_career_profile_target_roles__target_role_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                target_role_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TargetRoleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TargetRoleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_required_skill_api_v1_career_profile_target_roles__target_role_id__required_skills_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                target_role_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddRequiredSkillRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TargetRoleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_required_skill_api_v1_career_profile_target_roles__target_role_id__required_skills__skill_name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                target_role_id: string;
                skill_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TargetRoleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_required_skill_api_v1_career_profile_target_roles__target_role_id__required_skills__skill_name__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                target_role_id: string;
                skill_name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddRequiredSkillRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TargetRoleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_chat_message_api_v1_chat_messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendChatMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SendChatMessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_quote_of_the_day_api_v1_quote_of_the_day_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteOfTheDayResponse"];
                };
            };
        };
    };
    get_gap_analysis_api_v1_skills_gap_analysis_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GapAnalysisResponse"];
                };
            };
        };
    };
}
