"""cikg mvp2a search foundation

Revision ID: 074666e62403
Revises: 02e41ab151ce
Create Date: 2026-07-29 16:31:36.147580

Phase 4.5.1 MVP 2A per docs/architecture/cikg-mvp-roadmap.md /
cikg-semantic-search.md: hybrid search over the MVP 1 graph content.

Hand-written rather than autogenerated — pgvector's Vector column,
Postgres GENERATED ALWAYS AS ... STORED columns, and HNSW/GIN index
types aren't things Alembic's autogenerate models well, the same
reason bdc2e7597843/e8e87feda0bd used raw op.execute for RLS policies
and CHECK constraints respectively.

`embedding_models` mirrors `model_versions`' reference-data shape (no
tenant_id). `content_embeddings` is the polymorphic embedding store —
one row per (entity_type, entity_id, embedding_model_id), covering
`Skill`/`CikgRole`/`Competency` only (the only CIKG node types with
real free text; `SkillCategory` is excluded, same "purely structural"
carve-out cikg-semantic-search.md itself makes).

`search_vector` on skills/cikg_roles/competencies is a DB-generated
STORED tsvector column (name/title + description only — ats_keywords
is folded out for skills since it's JSON, not a Postgres array, and is
empty in all MVP 1 seed content; revisit if that changes) with a GIN
index, the full-text half of hybrid search.
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '074666e62403'
down_revision: str | None = '02e41ab151ce'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None

_EMBEDDING_DIMENSIONS = 768


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.create_table(
        'embedding_models',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('provider', sa.String(length=50), nullable=False),
        sa.Column('model_name', sa.String(length=100), nullable=False),
        sa.Column('dimensions', sa.Integer(), nullable=False),
        sa.Column('is_default', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_embedding_models')),
    )

    op.create_table(
        'content_embeddings',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('entity_type', sa.String(length=30), nullable=False),
        sa.Column('entity_id', sa.UUID(), nullable=False),
        sa.Column('embedding_model_id', sa.UUID(), nullable=False),
        sa.Column('embedding', Vector(_EMBEDDING_DIMENSIONS), nullable=False),
        sa.Column('source_text_hash', sa.String(length=64), nullable=False),
        sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(
            ['embedding_model_id'], ['embedding_models.id'],
            name=op.f('fk_content_embeddings_embedding_model_id_embedding_models'),
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_content_embeddings')),
        sa.UniqueConstraint(
            'entity_type', 'entity_id', 'embedding_model_id',
            name='uq_content_embeddings_entity_model',
        ),
    )
    op.create_index(
        "ix_content_embeddings_entity_type_entity_id",
        "content_embeddings",
        ["entity_type", "entity_id"],
    )
    op.execute(
        "CREATE INDEX ix_content_embeddings_embedding_hnsw ON content_embeddings "
        "USING hnsw (embedding vector_cosine_ops)"
    )

    op.execute(
        "ALTER TABLE skills ADD COLUMN search_vector tsvector "
        "GENERATED ALWAYS AS (to_tsvector('english', name || ' ' || coalesce(description, ''))) STORED"
    )
    op.execute("CREATE INDEX ix_skills_search_vector ON skills USING gin (search_vector)")

    op.execute(
        "ALTER TABLE cikg_roles ADD COLUMN search_vector tsvector "
        "GENERATED ALWAYS AS (to_tsvector('english', title || ' ' || coalesce(description, ''))) STORED"
    )
    op.execute("CREATE INDEX ix_cikg_roles_search_vector ON cikg_roles USING gin (search_vector)")

    op.execute(
        "ALTER TABLE competencies ADD COLUMN search_vector tsvector "
        "GENERATED ALWAYS AS (to_tsvector('english', name || ' ' || coalesce(description, ''))) STORED"
    )
    op.execute("CREATE INDEX ix_competencies_search_vector ON competencies USING gin (search_vector)")


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_competencies_search_vector")
    op.execute("ALTER TABLE competencies DROP COLUMN search_vector")
    op.execute("DROP INDEX IF EXISTS ix_cikg_roles_search_vector")
    op.execute("ALTER TABLE cikg_roles DROP COLUMN search_vector")
    op.execute("DROP INDEX IF EXISTS ix_skills_search_vector")
    op.execute("ALTER TABLE skills DROP COLUMN search_vector")

    op.execute("DROP INDEX IF EXISTS ix_content_embeddings_embedding_hnsw")
    op.drop_index("ix_content_embeddings_entity_type_entity_id", table_name="content_embeddings")
    op.drop_table('content_embeddings')
    op.drop_table('embedding_models')
    # Not dropping the `vector` extension — other features may depend on
    # it later, and DROP EXTENSION cascades in ways not worth risking on
    # a downgrade path.
