"""profile enrichment - photo competencies highlights achievements endorsements

Revision ID: 2634915dd706
Revises: c0af3c65e9ba
Create Date: 2026-07-19 10:22:48.515884

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2634915dd706'
down_revision: str | None = 'c0af3c65e9ba'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_highlights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('career_profile_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('occurred_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['career_profile_id'], ['career_profiles.id'], name=op.f('fk_career_highlights_career_profile_id_career_profiles')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_career_highlights_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_career_highlights'))
    )
    op.create_table('key_achievements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('career_profile_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('occurred_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['career_profile_id'], ['career_profiles.id'], name=op.f('fk_key_achievements_career_profile_id_career_profiles')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_key_achievements_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_key_achievements'))
    )
    op.create_table('peer_endorsements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('career_profile_id', sa.UUID(), nullable=False),
    sa.Column('recommender_name', sa.String(length=255), nullable=False),
    sa.Column('recommender_title', sa.String(length=255), nullable=True),
    sa.Column('relationship', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['career_profile_id'], ['career_profiles.id'], name=op.f('fk_peer_endorsements_career_profile_id_career_profiles')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_peer_endorsements_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_peer_endorsements'))
    )
    op.add_column('career_profiles', sa.Column('photo_url', sa.String(length=2048), nullable=True))
    op.add_column('career_profiles', sa.Column('core_competencies', sa.JSON(), nullable=False, server_default='[]'))
    # ### end Alembic commands ###
    # NOTE: as with the Phase 2 core migration, autogenerate proposed
    # dropping every imperatively-created index from prior migrations
    # (they aren't declared on the ORM models). Omitted deliberately —
    # see docs/architecture/backend-architecture.md.

    op.create_index(
        "ix_career_highlights_tenant_id_profile_id",
        "career_highlights",
        ["tenant_id", "career_profile_id"],
    )
    op.create_index(
        "ix_key_achievements_tenant_id_profile_id",
        "key_achievements",
        ["tenant_id", "career_profile_id"],
    )
    op.create_index(
        "ix_peer_endorsements_tenant_id_profile_id",
        "peer_endorsements",
        ["tenant_id", "career_profile_id"],
    )

    for table in ("career_highlights", "key_achievements", "peer_endorsements"):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY tenant_isolation_policy ON {table}
                USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
                WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid)
            """
        )


def downgrade() -> None:
    for table in ("career_highlights", "key_achievements", "peer_endorsements"):
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation_policy ON {table}")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('career_profiles', 'core_competencies')
    op.drop_column('career_profiles', 'photo_url')
    op.drop_table('peer_endorsements')
    op.drop_table('key_achievements')
    op.drop_table('career_highlights')
    # ### end Alembic commands ###
