"""add display order and company fields

Revision ID: 2be908e7e965
Revises: 2634915dd706
Create Date: 2026-07-22 18:34:40.393895

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2be908e7e965'
down_revision: str | None = '2634915dd706'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None

# (table, scope_column) — scope_column is what "reorder within" means for
# each entity: siblings under the same profile, or the same user.
_ORDERABLE_TABLES = [
    ("experiences", "career_profile_id"),
    ("educations", "career_profile_id"),
    ("certifications", "career_profile_id"),
    ("career_goals", "user_id"),
    ("career_highlights", "career_profile_id"),
    ("key_achievements", "career_profile_id"),
    ("peer_endorsements", "career_profile_id"),
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('career_highlights', sa.Column('company', sa.String(length=255), nullable=True))
    op.add_column('key_achievements', sa.Column('company', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###
    # NOTE: as with prior Phase 2 migrations, autogenerate also proposed
    # dropping every imperatively-created index from earlier migrations
    # (not declared on the ORM models) — omitted deliberately.

    # display_order is added with a server_default so this doesn't fail
    # on tables that already have rows (a plain NOT NULL column with no
    # default cannot be added to a non-empty table). The backfill below
    # then assigns real sequential values based on existing created_at
    # order, so pre-existing lists keep a sensible order the first time
    # a user opens them — not just every row equal to a placeholder 0.
    for table, _ in _ORDERABLE_TABLES:
        op.add_column(
            table, sa.Column("display_order", sa.Integer(), nullable=False, server_default="0")
        )

    # RLS blocks this backfill otherwise: Alembic runs with no
    # app.tenant_id session variable set, and these tables use FORCE ROW
    # LEVEL SECURITY, so the UPDATE below would silently affect zero
    # rows and leave every row at the server_default of 0 — caught by
    # actually inserting pre-migration test data and checking the result
    # before shipping this, not by inspecting the SQL alone. Disabling
    # RLS for the duration of the backfill (the table owner may do this
    # regardless of FORCE) and re-enabling it immediately after is the
    # correct fix — a cross-tenant data migration is exactly the
    # legitimate exception RLS needs to allow, scoped as tightly as
    # possible in the migration itself, never in application code.
    for table, _ in _ORDERABLE_TABLES:
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")

    for table, scope_column in _ORDERABLE_TABLES:
        op.execute(
            f"""
            WITH ranked AS (
                SELECT id, ROW_NUMBER() OVER (
                    PARTITION BY {scope_column} ORDER BY created_at ASC
                ) AS rn
                FROM {table}
            )
            UPDATE {table}
            SET display_order = ranked.rn
            FROM ranked
            WHERE {table}.id = ranked.id
            """
        )

    for table, _ in _ORDERABLE_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")

    # Composite indexes for the common "list this scope, ordered" query
    # shape — separate from (and in addition to) each table's existing
    # (tenant_id, scope) index from earlier migrations.
    for table, scope_column in _ORDERABLE_TABLES:
        op.create_index(
            f"ix_{table}_{scope_column}_display_order",
            table,
            [scope_column, "display_order"],
        )


def downgrade() -> None:
    for table, scope_column in _ORDERABLE_TABLES:
        op.drop_index(f"ix_{table}_{scope_column}_display_order", table_name=table)

    for table, _ in _ORDERABLE_TABLES:
        op.drop_column(table, "display_order")

    op.drop_column('key_achievements', 'company')
    op.drop_column('career_highlights', 'company')
