"""career profile core

Revision ID: c0af3c65e9ba
Revises: cde4f82abc35
Create Date: 2026-07-18 20:37:58.216358

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c0af3c65e9ba'
down_revision: str | None = 'cde4f82abc35'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_goals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('target_role', sa.String(length=255), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_career_goals_tenant_id_tenants')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_career_goals_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_career_goals'))
    )
    op.create_table('career_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('headline', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('career_readiness_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_career_profiles_tenant_id_tenants')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_career_profiles_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_career_profiles'))
    )
    op.create_table('career_profile_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('career_profile_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('change_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['career_profile_id'], ['career_profiles.id'], name=op.f('fk_career_profile_versions_career_profile_id_career_profiles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_career_profile_versions'))
    )
    op.create_table('certifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('career_profile_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('issuing_organization', sa.String(length=255), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('credential_id', sa.String(length=255), nullable=True),
    sa.Column('credential_url', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['career_profile_id'], ['career_profiles.id'], name=op.f('fk_certifications_career_profile_id_career_profiles')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_certifications_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_certifications'))
    )
    op.create_table('educations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('career_profile_id', sa.UUID(), nullable=False),
    sa.Column('institution', sa.String(length=255), nullable=False),
    sa.Column('degree', sa.String(length=255), nullable=True),
    sa.Column('field_of_study', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['career_profile_id'], ['career_profiles.id'], name=op.f('fk_educations_career_profile_id_career_profiles')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_educations_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_educations'))
    )
    op.create_table('experiences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('career_profile_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['career_profile_id'], ['career_profiles.id'], name=op.f('fk_experiences_career_profile_id_career_profiles')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_experiences_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiences'))
    )
    # ### end Alembic commands ###
    # NOTE: autogenerate also detected drop_index/drop_constraint calls
    # for indexes created imperatively in the Phase 1 migration (they
    # aren't declared on the ORM models, so autogenerate can't see them
    # as intentional and proposes removing them). Deliberately omitted
    # here — see docs/architecture/backend-architecture.md if this
    # migration is regenerated; always diff against intent, not just
    # accept autogenerate's output.

    # --- Composite indexes (docs/architecture/multi-tenancy-design.md) ---
    op.create_index("ix_career_profiles_tenant_id_user_id", "career_profiles", ["tenant_id", "user_id"])
    op.create_index(
        "ix_career_profile_versions_profile_id", "career_profile_versions", ["career_profile_id"]
    )
    op.create_index(
        "ix_experiences_tenant_id_profile_id", "experiences", ["tenant_id", "career_profile_id"]
    )
    op.create_index(
        "ix_educations_tenant_id_profile_id", "educations", ["tenant_id", "career_profile_id"]
    )
    op.create_index(
        "ix_certifications_tenant_id_profile_id", "certifications", ["tenant_id", "career_profile_id"]
    )
    op.create_index("ix_career_goals_tenant_id_user_id", "career_goals", ["tenant_id", "user_id"])

    # --- Row-Level Security ---
    # All six tables are strictly tenant-owned (exact-match policy, same
    # shape as Phase 1's organizations/users/user_roles/audit_events).
    # career_profile_versions is the one exception: it has no tenant_id
    # column of its own (see the model's docstring) — it's protected
    # transitively through its FK to career_profiles, since every read
    # path joins through CareerProfileVersionRepository.list_for_profile,
    # which is only ever called with a career_profile_id the caller
    # already owns (verified by the calling application service).
    for table in ("career_profiles", "experiences", "educations", "certifications", "career_goals"):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY tenant_isolation_policy ON {table}
                USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
                WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid)
            """
        )


def downgrade() -> None:
    for table in ("career_profiles", "experiences", "educations", "certifications", "career_goals"):
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation_policy ON {table}")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('experiences')
    op.drop_table('educations')
    op.drop_table('certifications')
    op.drop_table('career_profile_versions')
    op.drop_table('career_profiles')
    op.drop_table('career_goals')
    # ### end Alembic commands ###
