"""identity platform foundation

Revision ID: cde4f82abc35
Revises: 
Create Date: 2026-07-17 21:34:37.722907

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'cde4f82abc35'
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('code', name=op.f('uq_permissions_code'))
    )
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subdomain', sa.String(length=63), nullable=False),
    sa.Column('plan_tier', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants')),
    sa.UniqueConstraint('subdomain', name=op.f('uq_tenants_subdomain'))
    )
    op.create_table('feature_flags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_feature_flags_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feature_flags'))
    )
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_org_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_org_id'], ['organizations.id'], name=op.f('fk_organizations_parent_org_id_organizations')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_organizations_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_roles_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles')),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions'))
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_users_org_id_organizations')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_users_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('event_metadata', sa.JSON(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_audit_events_tenant_id_tenants')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_events_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_table('user_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_user_roles_org_id_organizations')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_user_roles_tenant_id_tenants')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_roles'))
    )
    # ### end Alembic commands ###

    # --- Composite indexes for tenant-scoped lookups ---
    # (docs/architecture/multi-tenancy-design.md: every tenant-owned table
    # gets a (tenant_id, <common filter column>) index.)
    op.create_index("ix_organizations_tenant_id", "organizations", ["tenant_id"])
    op.create_index("ix_users_tenant_id_email", "users", ["tenant_id", "email"])
    op.create_unique_constraint("uq_users_tenant_id_email", "users", ["tenant_id", "email"])
    op.create_index("ix_user_roles_tenant_id_user_id", "user_roles", ["tenant_id", "user_id"])
    op.create_index(
        "ix_audit_events_tenant_id_occurred_at", "audit_events", ["tenant_id", "occurred_at"]
    )
    op.create_index("ix_feature_flags_tenant_id", "feature_flags", ["tenant_id"])

    # --- Row-Level Security (docs/architecture/multi-tenancy-design.md) ---
    # Strictly tenant-owned tables: exact tenant_id match only.
    #
    # FORCE ROW LEVEL SECURITY is not optional here: by default, Postgres
    # exempts a table's OWNER from its own RLS policies (and superusers
    # are always exempt, full stop — the application's DB role must
    # never be a superuser in any real environment). Without FORCE, the
    # application's own connection role — which typically owns these
    # tables after running migrations — would silently bypass isolation
    # entirely.
    #
    # current_setting(..., true) (missing_ok=true) is deliberate, not a
    # simplification: a session where `app.tenant_id` has never been set
    # even once — a fresh pooled connection, an admin script, a seed
    # script — makes Postgres raise "unrecognized configuration
    # parameter" from plain current_setting(), not a graceful empty
    # result. missing_ok=true returns NULL instead, which then makes the
    # equality comparison false (never true), so the policy still fails
    # closed (zero rows) — just without crashing the caller outright.
    # Both behaviors were verified by hand-testing against a real
    # Postgres instance, not assumed from documentation.
    for table in ("organizations", "users", "user_roles", "audit_events"):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY tenant_isolation_policy ON {table}
                USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
                WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid)
            """
        )

    # Nullable-tenant tables: global rows (tenant_id IS NULL) are visible
    # to every tenant in addition to that tenant's own rows — and, since
    # global rows have no owning tenant to match, remain visible even to
    # sessions with no tenant context bound at all (this is exactly what
    # the seed script relies on to create global roles/permissions).
    for table in ("roles", "feature_flags"):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY tenant_isolation_policy ON {table}
                USING (tenant_id = current_setting('app.tenant_id', true)::uuid OR tenant_id IS NULL)
                WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid OR tenant_id IS NULL)
            """
        )

    # `tenants` and `permissions` are intentionally exempt from RLS — see
    # docs/architecture/multi-tenancy-design.md, "What's Exempt from
    # Tenant Scoping". `role_permissions` inherits protection through its
    # join to `roles`/`permissions` rather than needing its own policy.

    # --- Audit immutability: append-only, enforced at the database level ---
    op.execute(
        """
        CREATE OR REPLACE FUNCTION reject_audit_event_mutation()
        RETURNS TRIGGER AS $$
        BEGIN
            RAISE EXCEPTION 'audit_events rows are immutable and cannot be updated or deleted';
        END;
        $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        """
        CREATE TRIGGER audit_events_immutable
        BEFORE UPDATE OR DELETE ON audit_events
        FOR EACH ROW EXECUTE FUNCTION reject_audit_event_mutation()
        """
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS audit_events_immutable ON audit_events")
    op.execute("DROP FUNCTION IF EXISTS reject_audit_event_mutation()")

    for table in ("organizations", "users", "user_roles", "audit_events", "roles", "feature_flags"):
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation_policy ON {table}")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    op.drop_table('audit_events')
    op.drop_table('users')
    op.drop_table('role_permissions')
    op.drop_table('roles')
    op.drop_table('organizations')
    op.drop_table('feature_flags')
    op.drop_table('tenants')
    op.drop_table('permissions')
    # ### end Alembic commands ###
